INSERT INTO tb_user(email) VALUES ('maria@gmail.com');
INSERT INTO tb_user(email) VALUES ('joao@gmail.com');
INSERT INTO tb_user(email) VALUES ('ana@gmail.com');
INSERT INTO tb_user(email) VALUES ('lucia@gmail.com');
INSERT INTO tb_user(email) VALUES ('joaquim@gmail.com');

INSERT INTO tb_movie(score, count, title, image) VALUES (4.5, 2, 'After', 'https://static.fanpage.it/wp-content/uploads/sites/17/2020/10/after3.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (3.3, 3, 'Sex Education', 'https://superherobrasil.com.br/wp-content/uploads/2019/11/Sex-Education.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Euphoria', 'https://imagens.brasil.elpais.com/resizer/8Feq274d3N3V8DNmLOy5WS62itc=/1960x0/arc-anglerfish-eu-central-1-prod-prisa.s3.amazonaws.com/public/NOA6YXBL23QBCFBVMTMYNOXBSY.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'A Cinco Passos de Você', 'https://media.hugogloss.uol.com.br/uploads/2019/01/a-cinco-passos-de-voce-234823.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Mr. Robot', 'https://observatoriodocinema.uol.com.br/wp-content/uploads/2019/10/mr_robot.0.jpg.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'The Boys', 'https://uploads.jovemnerd.com.br/wp-content/uploads/2021/12/the-boys-ccxp-worlds.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Invencível', 'https://www.planocritico.com/wp-content/uploads/2021/04/invencivel-07-plano-critico.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O Lobo de Wall Street', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/cWUOv3H7YFwvKeaQhoAQTLLpo9Z.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Aves de Rapina: Arlequina e sua Emancipação Fantabulosa', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/jiqD14fg7UTZOT6qgvzTmfRYpWI.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Homem-Aranha: Sem Volta para Casa', 'https://sm.ign.com/ign_br/movie/h/homem-aran/homem-aranha-3_ybgv.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Na Mesma Onda', 'https://entreterse.com.br/wp-content/uploads/2021/03/na-mesma-onda-1.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Friends', 'https://t8j5n5j3.rocketcdn.me/wp-content/uploads/2020/08/friends-curiosidades-sobre-uma-das-maiores-series-de-todos-os-tempos-1024x576.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Vingadores: Ultimato', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Thor', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/cDJ61O1STtbWNBwefuqVrRe3d7l.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Cisne Negro', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/hqh5O4KssfJWI62HGAgrjHXbxhD.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O Silêncio dos Inocentes', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/mfwq2nMBzArzQ7Y9RKE8SKeeTkg.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Round 6', 'https://sm.ign.com/t/ign_br/screenshot/default/11-squidgame-unit-01_5m5e.1080.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Elite', 'https://br.web.img2.acsta.net/r_1280_720/newsv7/20/07/20/15/43/2415986.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Lúcifer', 'https://observatoriodocinema.uol.com.br/wp-content/uploads/2021/05/Lucifer-divulgacao-1.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Harry Potter e a Pedra Filosofal', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/lvOLivVeX3DVVcwfVkxKf0R22D8.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'You', 'https://tracklist.com.br/wp-content/uploads/2021/07/you-serie-netflix-3-temporada-e1596648859617.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Animais Fantásticos e Onde Habitam', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/8Qsr8pvDL3s1jNZQ4HK1d1Xlvnh.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'A Teoria de Tudo', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/kq2MHrRfH6RTfkvyDEmYLmGHE6U.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O Livro de Boba Fett', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/sjx6zjQI2dLGtEL0HGWsnq6UyLU.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Outer Banks', 'https://mixdeseries.com.br/wp-content/uploads/2021/07/Outer-Banks-3-temporada.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Interestelar', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Contato', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/yFkUPqBuUnbhYbQL8VFpTrAT9za.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Duna', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'La Casa de Papel', 'https://spinoff.com.br/wp-content/uploads/La-Casa-de-Papel-1.jpg');
INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 1, 5.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 2, 4.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 1, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 2, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 3, 4.0);